spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
     url: ${DATABASE_URL:jdbc:mysql://localhost:3306/carsharing}
     username: ${USERNAME:root}
     password: ${PASSWORD:root}
     driver-class-name: com.mysql.jdbc.Driver